### ISSUE TITLE
References and auto-complete don't work if item is indented.

### ISSUE THREAD

**Issue by gurrenm3** [maziac/asm-code-lens#108]
![image](https://github.com/user-attachments/assets/b90b7687-33b3-49d5-b7f8-7945bc33c2ec)
![image](https://github.com/user-attachments/assets/bc2772e1-0cfa-4c1f-ad77-7483d7843874)

You can see in the screenshots I provided that when something is indented it no longer is detected by asm code lens. It doesn't show references and doesn't show up in intellisense/code suggestions. It happens to at least variables and functions. Is there any way to fix this? I'm a beginner so not being able to indent things makes the code harder to read.

Thanks in advance

**Comment by maziac** [comment]
I'm not sure what assembler you are using.
The label/references in asm-code-lens are more or less assembler agnostic.
I.e. suggestions work on heuristics that are common to many assemblers.
(In contrast to the syntax highlighting that is available for z80 and x86).
That means: asm-code-lens does not know about e.g. "offset".
It would suggest what comes directly after the instruction (here "push") but not after "offset".
I guess that this is the problem here.
Indenting as such should not be a problem other than that asm-code-lens expects the labels at the start of the line.

BTW the suggestions are also mixed with suggestions that "vscode" invents. I.e. it is sometimes hard to understand the source of the suggestions.

**Comment by gurrenm3** [comment]
Sorry, due to my inexperience I didn't provided you enough information.

I'm using MASM as the assembler. Here is the template I'm working off of: https://github.com/gurrenm3/x86-Assembly-VSCode-Template. It includes my entire setup. I'm getting the references for my MASM32 files from my Visual Studio 2022 installation, which can also be seen in the `.vscode/build.ps1` file in my template. 

The problem I'm encountering is that if I indent the line a label is defined on, it seems to not be detected by asm code lens. As a result it doesn't show up in code suggestions and doesn't find it's references.

The screenshots I originally provided are just to demonstrate that references and code suggestions don't work on any labels (variables/functions) whose definition is indented. I didn't clarify this well earlier but in the first screenshot I indented `strNumberFormat` once in my `data` section. After doing that it stopped showing up in the code suggestions in my second screenshot, and also doesn't update to show any references.

I hope this is more clear, please let me know if I need to provide any additional information.

**Comment by maziac** [comment]
Ah, I see.

A label is recognized by asm-code-lens if either it starts with the first character in a line (no indentation) or if there are only white-spaces in front of the label and the label is suffixed by a ":"

If a label does not start at the beginning of a line and it is not suffixed by a ":" it could as well be a mnemonic or something else.
Without assembler specific (e.g. MASM, x86) knowledge it is not possible to tell if it is a label or not.
