### ISSUE TITLE
Inconsistent highlighting of registers

### ISSUE THREAD

**Issue by 0xallie** [maziac/asm-code-lens#58]
Using x86 ASM with GNU Assembler and Intel syntax. `ah`, `bh` and `ch` are highlighted in some light green color, `dh` is purple, and `sp` is a darker cyan. Other registers are light cyan.

![Screenshot of issue](https://user-images.githubusercontent.com/482367/117706048-1c87b580-b1cd-11eb-864f-66ba2aa2b592.png)

**Comment by maziac** [comment]
This extension started only with the z80 assembler grammar.
The intel syntax was added later. It is very basic also because the extension tries to allow z80 and intel in parallel.

It would be better to remove the grammars from the extension completely and have separate ones for z80 and intel in separate extensions.
But I'm no expert for intel syntax and then would probably do only the z80 syntax.
So this would not help you either.

Maybe the best would be that if you like you can do a fork and check if you can improve the intel grammar and contribute a PR.
I can then check if there are conflicts with the z80 and see if we can merge the PR into the extension.

I add also @andersonarc here, as he has contributed the intel grammar in the first place.
