### ISSUE TITLE
Hover tips aren't displayed properly

### ISSUE THREAD

**Issue by ArmoredPony** [maziac/asm-code-lens#75]
Hover tips seem broken to me. For example, this is what I get when I hover the cursor over `mov` command:
![2048](https://user-images.githubusercontent.com/61470425/190703458-50f8e9df-9af0-465b-9dc4-2f90e89896cd.png)

**Comment by maziac** [comment]
For hovering over an instruction asm-code-lens should normally not show anything.
Unless you used the "mov" also somewhere as a label.

So I think there are 2 problems here:
a) you have somewhere an instruction "mov es, ax ; ES - ...." that is interpreted as label most probably because it starts at column 0. 
b) I would guess there is a unicode problem or similar so that the characters are displayed wrongly.

Could you maybe zip your project and attach it here, or at least the file with the "mov" and the comment " ; ES -".

**Comment by ArmoredPony** [comment]
My bad, I actually have this instruction in another file and there is also a unicode problem. I copied the file into another directory and no tips are shown. Sorry for opening that issue. I'm very new to assembly so I didn't even notice that `mov es,ax` doesn't match to my actual code.

**Comment by AntonBogun** [comment]
Are there no plans to add tooltips when hovering over an instruction?
I was looking for something to help learn assembly when starting out and not remembering what each op stands for and does, and this extension seems to be almost there but it has the serious downside of not helping out with the instructions :(

**Comment by maziac** [comment]
Assembly language is not just  ONE language.
You need to know WHICH assembly language you want to use. Then you can look for an extension that helps you with the opcodes.

**Comment by AntonBogun** [comment]
I don't think there's any extensions that add hover for e.g. x86-64 assembly?
Most I could find was a syntax highligher

**Comment by maziac** [comment]
Asm-code-lens does not provide hover tooltips for any specific assembly language..
It tries to be agnostic to the assembly language opcodes and mainly supports you with the labels.
The exception is the syntax highlighting and I'm thinking (for a ling time) to remove it because of this inconsistency.
I started with syntax highlighting for the z80.
A few other people added the x86 highlighting..
But it would be better to separate in different  extensions.

So, all in all: No, there is no hover support for x86 opcodes in asm-code-lens.
